### PR TITLE
Changed call to PyShadowString constructor to fit Jython's current constructor

### PR DESCRIPTION
**Pull request by CalumFreeman**

### CODE REVIEW

**Comment by Stewori** [comment]
Interesting. I thought I had tested to build and use JyNI with Jython's development tip.
Anyway, your fix looks good and simplistic is fine as the issue was only caused by a refactoring. I would however recommend a small change and go for the ``PyObject``/``PyObject`` constructor rather than ``String``/``String`` as it is converted back to ``PyString`` anyway. I.e.
``PySystemState.prefix = new PyShadowString(PySystemState.prefix, pyHome);``

Thanks for this work!

**Comment by CalumFreeman** [comment]
I've amended the commit to use the preferred constructor.

**Comment by Stewori** [comment]
Ah, alright. Sorry for overlooking this.

**Comment by Stewori** [comment]
The solution is definitely fine, I can take over the part of assuring Windows compatibility. However I currently cannot tell when I find time. I hope it doesn't hinder your work if this PR isn't merged right now.
It would be good if you could check that it still works with Jython 2.7.1; this should be the case as the ``String``/``String`` constructor was already there yet. Background is that I would like to make a last 2.7.1 compatible release (JyNI alpha 5.1) before we commit the first PR that definitely breaks Jython 2.7.1 compatibility. After such a PR the next release would be contrained to happen after Jython 2.7.2 was released and it's unclear when that will happen (it's said to happen ASAP though, but there's still kind of a todo list, see discussion at http://bugs.jython.org/issue2694).

**Comment by CalumFreeman** [comment]
I've reconfigured/fixed the tree on my fork so this pull request has closed. I'll resubmit the request when I've checked the commit will work in version 2.7.1

**Comment by CalumFreeman** [comment]
Sorry I took a while to check this, I forgot about it. I'm starting to tidy things up now since I only have a few working days left before I'm back at uni.

I've tried building with 2.7.1 and it seems to work, the `String`/`String` constructor is in jython 2.7.1 so it builds fine and runs the JyNIDemo.py file. The code running PyShadowString stuff is commented out though, I'm not sure why.

Not having this PR hasn't been a problem, I just had a stashed commit (along with makefile path changes for my setup) that I applied whenever it was needed.

**Comment by Stewori** [comment]
I am already planning to make this compatible on Jython side again. A simple thing like this shouldn't break Jython 2.7.1 compatibility. So don't spend more work on this than necessary. I just cannot promise when I will find time to change stuff back at Jython.

**Pull request closed without merging**
